In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_movies = df_movies[['imdb_title_id', 'title', 'year', 'genre', 'country']]
df_movies

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [3]:
df_ratings = pd.read_csv('IMDb ratings.csv', low_memory=False)
df_ratings = df_ratings[['imdb_title_id','total_votes', 'mean_vote']]
df_ratings

      imdb_title_id  total_votes  mean_vote
0         tt0000009          154        5.9
1         tt0000574          589        6.3
2         tt0001892          188        6.0
3         tt0002101          446        5.3
4         tt0002130         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

# Concat() - Vertically(stacked, need common columns) and Horizontally

![Alt text](./Concat.png)

### Concatenate Vertically

In [4]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                   'age': [30, 90, 78, 80]})
df2 = pd.DataFrame({'id': ['E', 'F', 'G', 'H'],
                   'age': [30, 90, 78, 80]})
df = pd.concat([df1, df2], axis = 0, ignore_index = True)
df

  id  age
0  A   30
1  B   90
2  C   78
3  D   80
4  E   30
5  F   90
6  G   78
7  H   80

In [5]:
# extract 50% of the sample from df_movies
df_sample = df_movies.sample(frac=0.5, random_state = 1)
df_sample

,imdb_title_id,title,year,genre,country
4683,tt0036711,Vacanze a Natale,1944,"Crime, Drama, Film-Noir",USA
28176,tt0110216,Junior,1994,"Comedy, Romance, Sci-Fi",USA
16686,tt0071914,Nitten røde roser,1974,Crime,Denmark
76981,tt5178660,Rosso Mille Miglia,2015,Comedy,Italy
79161,tt5946668,4/20 Massacre,2018,"Action, Horror",USA
...,...,...,...,...,...
68910,tt2866708,Strange But True,2019,Thriller,Canada
856,tt0020697,L'angelo azzurro,1930,"Drama, Music",Germany
40896,tt0296591,17 fois Cécile Cassard,2002,Drama,France
78673,tt5785200,Machine,2017,"Action, Mystery, Romance",India
11621,tt0057469,"Sandokan, la tigre di Mompracem",1963,"Action, Adventure","Italy, France, Spain"

In [6]:
df_sample.shape

(42928, 5)

In [7]:
df_concat_vertically = pd.concat([df_movies, df_sample], axis = 0, ignore_index = True)
df_concat_vertically

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
128778,tt2866708,Strange But True,2019,Thriller,Canada
128779,tt0020697,L'angelo azzurro,1930,"Drama, Music",Germany
128780,tt0296591,17 fois Cécile Cassard,2002,Drama,France
128781,tt5785200,Machine,2017,"Action, Mystery, Romance",India
128782,tt0057469,"Sandokan, la tigre di Mompracem",1963,"Action, Adventure","Italy, France, Spain"

In [8]:
df_concat_vertically.shape

(128783, 5)

# Concatenate Horizontally (next to each other) - concats based on a common column

In [9]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                   'age': [30, 90, 78, 80]})
df2 = pd.DataFrame({'Job': ['Doctor', 'Statistician', 'Accountant', 'Developer']})
df = pd.concat([df1, df2], axis = 1)
df

  id  age           Job
0  A   30        Doctor
1  B   90  Statistician
2  C   78    Accountant
3  D   80     Developer

In [10]:
# df_movies.set_index('imdb_title_id', inplace = True)
# df_ratings.set_index('imdb_title_id', inplace = True)
df_concat_horizontally = pd.concat([df_movies, df_ratings], axis = 1, sort = True)
df_concat_horizontally.head()

,imdb_title_id,title,year,genre,country,imdb_title_id,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,tt0000009,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,tt0000574,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",tt0001892,188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,tt0002101,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,tt0002130,2237,6.9

In [11]:
df_concat_horizontally.shape

(85855, 8)

# Joins using merge()

### Inner Join - Intersection between dataframes (Common Columns)

In [12]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                   'age': [30, 90, 78, 80]})
df2 = pd.DataFrame({'id': ['C', 'D', 'G', 'H'],
                   'Job': ['Doctor', 'Statistician', 'Accountant', 'Developer']})
df_inner_join = df1.merge(df2,on = 'id', how = 'inner' )
df_inner_join

  id  age           Job
0  C   78        Doctor
1  D   80  Statistician

In [13]:
# Exercise
df_merge = df_movies.merge(df_ratings, on = 'imdb_title_id', how = 'inner')
pd.merge(df_movies, df_ratings, on= 'imdb_title_id')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

# Full Join (Outer) - Union

In [14]:
df1.merge(df2, on = 'id', how = 'outer')

  id   age           Job
0  A  30.0           NaN
1  B  90.0           NaN
2  C  78.0        Doctor
3  D  80.0  Statistician
4  G   NaN    Accountant
5  H   NaN     Developer

In [15]:
df1.merge(df2, on = 'id', how = 'outer').shape

(6, 3)

In [16]:
# Exercise
df_movies.merge(df_ratings, on = 'imdb_title_id', how = 'outer')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

# Exclusive Full Join
![Alt text](./Exclusive_Full_Join.png)

In [17]:
df1.merge(df2, on = 'id', how = 'outer')

  id   age           Job
0  A  30.0           NaN
1  B  90.0           NaN
2  C  78.0        Doctor
3  D  80.0  Statistician
4  G   NaN    Accountant
5  H   NaN     Developer

In [18]:
df1.merge(df2, on = 'id', how = 'outer', indicator = True) # makes a column called _merge which shows which row are in left, right, both

  id   age           Job      _merge
0  A  30.0           NaN   left_only
1  B  90.0           NaN   left_only
2  C  78.0        Doctor        both
3  D  80.0  Statistician        both
4  G   NaN    Accountant  right_only
5  H   NaN     Developer  right_only

In [19]:
df1.merge(df2, on = 'id', how = 'outer', indicator = True).query("_merge == 'left_only' or _merge == 'right_only' ")

  id   age         Job      _merge
0  A  30.0         NaN   left_only
1  B  90.0         NaN   left_only
4  G   NaN  Accountant  right_only
5  H   NaN   Developer  right_only

In [20]:
#exercise
df_movies.merge(df_ratings, on = 'imdb_title_id', how = 'outer', indicator = True).query("_merge == 'left_only' or _merge == 'right_only' ")

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

# Left Join 
![Alt text](./Left_Join.png)

In [21]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                   'age': [30, 90, 78, 80]})
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'], 'Job': ['Doctor', 'Statistician', 'Accountant', 'Developer']})
df1.merge(df2, on = 'id', how = 'left')

  id  age           Job
0  A   30           NaN
1  B   90           NaN
2  C   78        Doctor
3  D   80  Statistician

In [22]:
# Exercise
df_movies_sample = df_movies.sample(frac = 0.5, random_state = 1)
df_left = df_movies_sample.merge(df_ratings, on = 'imdb_title_id', how = 'left')

In [23]:
df_left.shape

(42928, 7)

# Exclusive Left Join
![Alt text](./Exclusive_Left_Join.png)

In [24]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                   'age': [30, 90, 78, 80]})
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'], 'Job': ['Doctor', 'Statistician', 'Accountant', 'Developer']})
df1.merge(df2, on = 'id', how = 'outer', indicator = True).query("_merge == 'left_only'")

  id   age  Job     _merge
0  A  30.0  NaN  left_only
1  B  90.0  NaN  left_only

In [26]:
# Exercise
df_movies_copy = df_movies
df_movies_copy.loc[:999, "imdb_title_id"] = 'tt1234567890'

In [27]:
df_exclusive_left = df_movies_copy.merge(df_ratings, on = 'imdb_title_id',how = 'outer', indicator = True).query("_merge == 'left_only' ")

In [28]:
df_exclusive_left

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
55817,tt1234567890,Miss Jerry,1894,Romance,USA,NaN,NaN,left_only
55818,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,NaN,NaN,left_only
55819,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark",NaN,NaN,left_only
55820,tt1234567890,Cleopatra,1912,"Drama, History",USA,NaN,NaN,left_only
55821,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...
56812,tt1234567890,Agente segreto Z1,1930,Drama,USA,NaN,NaN,left_only
56813,tt1234567890,Tom Sawyer,1930,"Adventure, Comedy, Drama",USA,NaN,NaN,left_only
56814,tt1234567890,Tonka Sibenice,1930,Drama,"Czechoslovakia, Germany",NaN,NaN,left_only
56815,tt1234567890,Top Speed,1930,"Comedy, Musical, Romance",USA,NaN,NaN,left_only
56816,tt1234567890,True to the Navy,1930,"Action, Comedy, Romance",USA,NaN,NaN,left_only