# One hash is Title
## double hash is sub-title

In [67]:
def printing():
    for i in range(0,10,2):
        print(i)

In [68]:
print("Hello World")

Hello World

In [69]:
"Hello World"

'Hello World'

In [70]:
print(type("Hello World"))
print("Hello World".upper())
print("Hello World".lower())
print("Hello World".title())
print("Hello World".count('l'))
print("Hello World".replace('l', 'u'))

<class 'str'>
HELLO WORLD
hello world
Hello World
3
Heuuo Worud

In [71]:
names = ['me', 'myself', 'i']
del names[0]
names

['myself', 'i']

# Sorting

In [72]:
numbers =[3,2,7,8,3,4,6,9]
numbers.sort(reverse = True)
numbers

[9, 8, 7, 6, 4, 3, 3, 2]

# Copying

In [73]:
new_names = names[:]
print(new_names)
new_names2 = names.copy()
print(new_names2)

['myself', 'i']
['myself', 'i']

## Dictionary

In [74]:
my_dict = {'name': 'Animesh', 'age': 21}
print(my_dict.keys())
print(my_dict.values())
print(my_dict.items())

dict_keys(['name', 'age'])
dict_values(['Animesh', 21])
dict_items([('name', 'Animesh'), ('age', 21)])

my_dict['height'] = 1.7
print(my_dict)
my_dict.update({'height': 1.8})
print(my_dict)
new_dict = my_dict.copy() #doesn't update
print(new_dict)
new_dict = my_dict #updates
print(new_dict)

In [75]:
del my_dict['name']
print(my_dict)

{'age': 21}

In [76]:
for i, name in enumerate(names):
    print(f"{i} - {name}")

0 - myself
1 - i

# Modules
## OS

In [77]:
import os
print(os.getcwd()) #gets current working directory
print(os.listdir())

/Users/animesh.tirkey/Desktop/DSA_C++
['cmake-build-debug', '.DS_Store', 'Web Scraping.ipynb', 'StudentsPerformance.csv', 'Data_Science.ipynb', 'Arrays.cpp', 'Arrays', 'Stat413_Assignment2.ipynb', '.ipynb_checkpoints', '.idea']

In [78]:
# os.mkdir("New New Folder")
# print(os.listdir())

# ***PANDAS***

## ***Creating a Dataframe from an array***

In [79]:
import pandas as pd
import numpy as np

In [80]:
# creating an array
data = np.array([[1,4],[2,5],[3,6]])

In [81]:
# creating a dataframe
df = pd.DataFrame(data, index = ['row1', 'row2', 'row3'], columns = ['col1', 'col2'])

In [82]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# Creating a DataFrame from a Dictionary

In [83]:
states = ["AB", "BC", 'MB']
population = [1,2,3]
dict_states = {"States":states, 'Population':population} 
df_population = pd.DataFrame(dict_states, index=['State 1', 'State 2', 'State 3'])

In [84]:
df_population

        States  Population
State 1     AB           1
State 2     BC           2
State 3     MB           3

# DataFrame from a CSV

In [85]:
df_exams = pd.read_csv("StudentsPerformance.csv")
df_exams.head() #first 5 rows

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [86]:
df_exams.tail() #last 5 rows

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [87]:
# show last n rows
df_exams.head(10)
df_exams.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [88]:
df_exams.shape

(1000, 8)

In [89]:
# display n rows
pd.set_option('display.max_rows', 1000) #this will be the default behavior of the dataframe
pd.reset_option('display.max_rows')
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Pandas Attribute, Functions and methods

# Attribute

In [90]:
df_exams.shape

(1000, 8)

In [91]:
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [92]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [93]:
df_exams.dtypes #type of each column

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

# Methods

In [94]:
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [95]:
df_exams.info() #summary info of the dataframe

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [96]:
df_exams.describe() #statistics of the dataFrame

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Functions

In [97]:
len(df_exams) # no. of rows

1000

In [98]:
max(df_exams.index) # max number in the number of rows

999

In [99]:
min(df_exams.index)

0

In [100]:
type(df_exams)

pandas.DataFrame

In [101]:
# rounding values in the DataFrame
round(df_exams, 2) # only works with floats

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Selecting One Column

In [102]:
df_exams['gender'] #preferred to use this

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: str

In [103]:
type(df_exams['gender'])

pandas.Series

In [104]:
df_exams['gender'].index

RangeIndex(start=0, stop=1000, step=1)

In [105]:
df_exams.gender.head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: str

# Selecting 2 or more Columns

In [106]:
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [107]:
df_exams[['gender', 'math score']] # same order

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [108]:
type(df_exams[['gender', 'math score']]) #when using 2 pairs of sq brackets we get a DATAFRAME, when using one only we get a SERIES!

pandas.DataFrame

In [109]:
df_exams[['writing score', 'gender', 'math score', 'reading score']]

     writing score  gender  math score  reading score
0               74  female          72             72
1               88  female          69             90
2               93  female          90             95
3               44    male          47             57
4               75    male          76             78
..             ...     ...         ...            ...
995             95  female          88             99
996             55    male          62             55
997             65  female          59             71
998             77  female          68             78
999             86  female          77             86

[1000 rows x 4 columns]

In [110]:
#we can't select 2 or more columns using the . sign

# Adding a new column

In [111]:
# adding a new column
df_exams['language score'] = 70 # all 70 in the rows
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

In [112]:
#create an array with 1000 elements
language_score = np.arange(0,1000)

In [113]:
len(np.arange(0,1000))

1000

In [114]:
# adding a new column with a dataframe
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [115]:
#create random integers numbers between 0 and 100
int_language_score = np.random.randint(1,101,size = 1000)

In [116]:
min(int_language_score)
max(int_language_score)

np.int64(100)

In [117]:
df_exams['language score'] = int_language_score
df_exams # now we have random integers!

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,31
2,female,group B,master's degree,standard,none,90,95,93,66
3,male,group A,associate's degree,free/reduced,none,47,57,44,13
4,male,group C,some college,standard,none,76,78,75,43
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,26
996,male,group C,high school,free/reduced,none,62,55,55,44
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,45
999,female,group D,some college,free/reduced,none,77,86,86,73

In [118]:
#create random float
float_language_score = np.round(np.random.uniform(1, 101, size=1000), decimals = 2)
df_exams['language score'] = float_language_score
df_exams # now we have random floats!

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,52.40
1,female,group C,some college,standard,completed,69,90,88,43.64
2,female,group B,master's degree,standard,none,90,95,93,92.09
3,male,group A,associate's degree,free/reduced,none,47,57,44,3.89
4,male,group C,some college,standard,none,76,78,75,90.72
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,10.98
996,male,group C,high school,free/reduced,none,62,55,55,45.73
997,female,group C,high school,free/reduced,completed,59,71,65,83.28
998,female,group D,some college,standard,completed,68,78,77,97.06
999,female,group D,some college,free/reduced,none,77,86,86,17.74

# Adding a new column using Assign()
## Use when
* Add multiple columns in a single line of code
* When you need to overwrite the values of existing columns [BEST PRACTICE]

In [119]:
score1 = np.random.randint(1,100, size = 1000)
score2 = np.random.randint(1,100, size = 1000)
score3 = np.random.randint(100,201, size = 1000)

In [120]:
series1 = pd.Series(score1, index = np.arange(0,1000)) # A column made from score1 values added to a column name called series1
series2 = pd.Series(score2, index = np.arange(0,1000))
series3 = pd.Series(score3, index = np.arange(0,1000))

In [129]:
df_exams = df_exams.assign(score1 = series1, score2 = series2)
del df_exams['score3'] 
df_exams.insert(2,'score3', series3)

# adding 2 columns called 'score1' and 'score2'
# Need to reassign the DataFrame

In [130]:
df_exams

,gender,race/ethnicity,score3,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,184,bachelor's degree,standard,none,72,72,74,52.40,71,54
1,female,group C,127,some college,standard,completed,69,90,88,43.64,71,56
2,female,group B,117,master's degree,standard,none,90,95,93,92.09,14,39
3,male,group A,172,associate's degree,free/reduced,none,47,57,44,3.89,45,99
4,male,group C,106,some college,standard,none,76,78,75,90.72,5,39
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,161,master's degree,standard,completed,88,99,95,10.98,21,58
996,male,group C,197,high school,free/reduced,none,62,55,55,45.73,19,7
997,female,group C,168,high school,free/reduced,completed,59,71,65,83.28,77,20
998,female,group D,181,some college,standard,completed,68,78,77,97.06,22,66
999,female,group D,144,some college,free/reduced,none,77,86,86,17.74,2,12

# insert() - inserts a column at a specific position

In [100]:
#using index() to add a column at a specific position
df_exams.insert(1, 'test', series1) # adding the test column to the 1st index, 0th index is gender

In [101]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,25,group B,bachelor's degree,standard,none,72,72,74,10.47,25,18
1,female,71,group C,some college,standard,completed,69,90,88,43.69,71,71
2,female,6,group B,master's degree,standard,none,90,95,93,30.43,6,61
3,male,44,group A,associate's degree,free/reduced,none,47,57,44,10.26,44,51
4,male,76,group C,some college,standard,none,76,78,75,100.43,76,20
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,26,group E,master's degree,standard,completed,88,99,95,36.88,26,91
996,male,45,group C,high school,free/reduced,none,62,55,55,18.17,45,36
997,female,58,group C,high school,free/reduced,completed,59,71,65,15.83,58,2
998,female,61,group D,some college,standard,completed,68,78,77,89.59,61,86
999,female,22,group D,some college,free/reduced,none,77,86,86,41.53,22,82

# Math Operations

## Operations in columns

In [103]:
# select a column and calculate the total sum
df_exams['math score'].sum()

np.int64(66089)

In [110]:
df_exams['math score'].count()
df_exams['math score'].mean()
df_exams['math score'].std()
df_exams['math score'].max()
df_exams['math score'].min()

np.int64(0)

In [111]:
df_exams.describe()

,test,math score,reading score,writing score,language score,score1,score2
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,49.824000,66.08900,69.169000,68.054000,51.252630,49.824000,52.042000
std,27.983747,15.16308,14.600192,15.195657,29.102797,27.983747,28.030947
min,1.000000,0.00000,17.000000,10.000000,1.080000,1.000000,1.000000
25%,26.000000,57.00000,59.000000,57.750000,25.967500,26.000000,28.750000
50%,49.000000,66.00000,70.000000,69.000000,50.635000,49.000000,54.000000
75%,73.000000,77.00000,79.000000,79.000000,77.227500,73.000000,76.250000
max,99.000000,100.00000,100.000000,100.000000,100.980000,99.000000,99.000000

# Operations in Rows

In [113]:
# calculating sum in the row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'] #outputs index -> row

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [119]:
#Average 
df_exams = df_exams.assign(Average = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3).round(2)
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average,Average
0,female,25,group B,bachelor's degree,standard,none,72,72,74,10.47,25,18,72.67,72.67
1,female,71,group C,some college,standard,completed,69,90,88,43.69,71,71,82.33,82.33
2,female,6,group B,master's degree,standard,none,90,95,93,30.43,6,61,92.67,92.67
3,male,44,group A,associate's degree,free/reduced,none,47,57,44,10.26,44,51,49.33,49.33
4,male,76,group C,some college,standard,none,76,78,75,100.43,76,20,76.33,76.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,26,group E,master's degree,standard,completed,88,99,95,36.88,26,91,94.00,94.00
996,male,45,group C,high school,free/reduced,none,62,55,55,18.17,45,36,57.33,57.33
997,female,58,group C,high school,free/reduced,completed,59,71,65,15.83,58,2,65.00,65.00
998,female,61,group D,some college,standard,completed,68,78,77,89.59,61,86,74.33,74.33
999,female,22,group D,some college,free/reduced,none,77,86,86,41.53,22,82,83.00,83.00

# Value Count

In [123]:
#len function
len(df_exams['gender'])
#count method
df_exams['gender'].count()

np.int64(1000)

In [125]:
#counting gender elements by category
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [126]:
# relative frequecy in each category
df_exams['gender'].value_counts(normalize = True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [128]:
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [129]:
df_exams['parental level of education'].value_counts(normalize = True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

# sort a DataFrame

In [135]:
#sort a column
df_exams.sort_values('math score')

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average,Average
59,female,72,group C,some high school,free/reduced,none,0,17,10,73.55,72,11,9.00,9.00
980,female,34,group B,high school,free/reduced,none,8,24,23,42.07,34,48,18.33,18.33
17,female,62,group B,some high school,free/reduced,none,18,32,28,35.93,62,88,26.00,26.00
787,female,74,group B,some college,standard,none,19,38,32,9.99,74,58,29.67,29.67
145,female,24,group C,some college,free/reduced,none,22,39,33,40.20,24,92,31.33,31.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,male,19,group D,some college,standard,completed,100,97,99,29.82,19,99,98.67,98.67
623,male,57,group A,some college,standard,completed,100,96,86,83.94,57,21,94.00,94.00
451,female,18,group E,some college,standard,none,100,92,97,76.09,18,78,96.33,96.33
962,female,83,group E,associate's degree,standard,none,100,100,100,88.85,83,3,100.00,100.00
149,male,77,group E,associate's degree,free/reduced,completed,100,100,93,60.02,77,39,97.67,97.67

In [134]:
df_exams.sort_values('math score', ascending = False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average,Average
962,female,83,group E,associate's degree,standard,none,100,100,100,88.85,83,3,100.00,100.00
625,male,19,group D,some college,standard,completed,100,97,99,29.82,19,99,98.67,98.67
458,female,76,group E,bachelor's degree,standard,none,100,100,100,72.05,76,92,100.00,100.00
623,male,57,group A,some college,standard,completed,100,96,86,83.94,57,21,94.00,94.00
451,female,18,group E,some college,standard,none,100,92,97,76.09,18,78,96.33,96.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,24,group C,some college,free/reduced,none,22,39,33,40.20,24,92,31.33,31.33
787,female,74,group B,some college,standard,none,19,38,32,9.99,74,58,29.67,29.67
17,female,62,group B,some high school,free/reduced,none,18,32,28,35.93,62,88,26.00,26.00
980,female,34,group B,high school,free/reduced,none,8,24,23,42.07,34,48,18.33,18.33
59,female,72,group C,some high school,free/reduced,none,0,17,10,73.55,72,11,9.00,9.00

In [138]:
# sort descending by multiple columns
df_exams.sort_values(['math score', 'reading score'], ascending = False) #sorted first by math score(priority) and then reading score.
#doesn't update the dataFrame

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average,Average
149,male,77,group E,associate's degree,free/reduced,completed,100,100,93,60.02,77,39,97.67,97.67
458,female,76,group E,bachelor's degree,standard,none,100,100,100,72.05,76,92,100.00,100.00
916,male,97,group E,bachelor's degree,standard,completed,100,100,100,65.52,97,64,100.00,100.00
962,female,83,group E,associate's degree,standard,none,100,100,100,88.85,83,3,100.00,100.00
625,male,19,group D,some college,standard,completed,100,97,99,29.82,19,99,98.67,98.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,24,group C,some college,free/reduced,none,22,39,33,40.20,24,92,31.33,31.33
787,female,74,group B,some college,standard,none,19,38,32,9.99,74,58,29.67,29.67
17,female,62,group B,some high school,free/reduced,none,18,32,28,35.93,62,88,26.00,26.00
980,female,34,group B,high school,free/reduced,none,8,24,23,42.07,34,48,18.33,18.33
59,female,72,group C,some high school,free/reduced,none,0,17,10,73.55,72,11,9.00,9.00

In [139]:
df_exams.sort_values(['math score', 'reading score'], ascending = False, inplace = True)

In [140]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average,Average
149,male,77,group E,associate's degree,free/reduced,completed,100,100,93,60.02,77,39,97.67,97.67
458,female,76,group E,bachelor's degree,standard,none,100,100,100,72.05,76,92,100.00,100.00
916,male,97,group E,bachelor's degree,standard,completed,100,100,100,65.52,97,64,100.00,100.00
962,female,83,group E,associate's degree,standard,none,100,100,100,88.85,83,3,100.00,100.00
625,male,19,group D,some college,standard,completed,100,97,99,29.82,19,99,98.67,98.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,24,group C,some college,free/reduced,none,22,39,33,40.20,24,92,31.33,31.33
787,female,74,group B,some college,standard,none,19,38,32,9.99,74,58,29.67,29.67
17,female,62,group B,some high school,free/reduced,none,18,32,28,35.93,62,88,26.00,26.00
980,female,34,group B,high school,free/reduced,none,8,24,23,42.07,34,48,18.33,18.33
59,female,72,group C,some high school,free/reduced,none,0,17,10,73.55,72,11,9.00,9.00

In [141]:
#sort by text
df_exams.sort_values('race/ethnicity', ascending = True, key = lambda col:col.str.lower())
# lambda says use the column(col) : use col and use the string attribute in lower case.

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average,Average
741,female,86,group A,associate's degree,free/reduced,none,37,57,56,94.37,86,27,50.00,50.00
151,male,26,group A,bachelor's degree,standard,none,77,67,68,34.62,26,6,70.67,70.67
811,male,35,group A,high school,free/reduced,none,45,47,49,64.67,35,58,47.00,47.00
112,male,58,group A,associate's degree,standard,none,54,53,47,20.92,58,46,51.33,51.33
25,male,11,group A,master's degree,free/reduced,none,73,74,72,38.99,11,75,73.00,73.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,male,12,group E,some college,standard,none,68,72,65,32.30,12,85,68.33,68.33
915,female,79,group E,some college,standard,none,68,70,66,1.08,79,47,68.00,68.00
592,male,13,group E,bachelor's degree,standard,none,68,68,64,71.86,13,24,66.67,66.67
479,male,67,group E,associate's degree,standard,none,76,71,67,32.81,67,22,71.33,71.33
517,female,39,group E,some college,standard,completed,66,74,73,90.61,39,4,71.00,71.00

# Create Index

In [142]:
import random

In [144]:
#creating non repetitive values for the index
new_index = np.arange(0,1000)

In [145]:
#shuffling the indexes to sort it later
random.shuffle(new_index)

In [146]:
#create a new column with new index
df_exams['new_index'] = new_index
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average,Average,new_index
149,male,77,group E,associate's degree,free/reduced,completed,100,100,93,60.02,77,39,97.67,97.67,843
458,female,76,group E,bachelor's degree,standard,none,100,100,100,72.05,76,92,100.00,100.00,48
916,male,97,group E,bachelor's degree,standard,completed,100,100,100,65.52,97,64,100.00,100.00,550
962,female,83,group E,associate's degree,standard,none,100,100,100,88.85,83,3,100.00,100.00,478
625,male,19,group D,some college,standard,completed,100,97,99,29.82,19,99,98.67,98.67,337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,24,group C,some college,free/reduced,none,22,39,33,40.20,24,92,31.33,31.33,354
787,female,74,group B,some college,standard,none,19,38,32,9.99,74,58,29.67,29.67,386
17,female,62,group B,some high school,free/reduced,none,18,32,28,35.93,62,88,26.00,26.00,388
980,female,34,group B,high school,free/reduced,none,8,24,23,42.07,34,48,18.33,18.33,236
59,female,72,group C,some high school,free/reduced,none,0,17,10,73.55,72,11,9.00,9.00,642

# Set Index

In [149]:
# set new_index col as index
df_exams.set_index('new_index', inplace = True)
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average,Average
new_index,,,,,,,,,,,,,,
843,male,77,group E,associate's degree,free/reduced,completed,100,100,93,60.02,77,39,97.67,97.67
48,female,76,group E,bachelor's degree,standard,none,100,100,100,72.05,76,92,100.00,100.00
550,male,97,group E,bachelor's degree,standard,completed,100,100,100,65.52,97,64,100.00,100.00
478,female,83,group E,associate's degree,standard,none,100,100,100,88.85,83,3,100.00,100.00
337,male,19,group D,some college,standard,completed,100,97,99,29.82,19,99,98.67,98.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,female,24,group C,some college,free/reduced,none,22,39,33,40.20,24,92,31.33,31.33
386,female,74,group B,some college,standard,none,19,38,32,9.99,74,58,29.67,29.67
388,female,62,group B,some high school,free/reduced,none,18,32,28,35.93,62,88,26.00,26.00
236,female,34,group B,high school,free/reduced,none,8,24,23,42.07,34,48,18.33,18.33
642,female,72,group C,some high school,free/reduced,none,0,17,10,73.55,72,11,9.00,9.00

# sort INdex

In [150]:
df_exams.sort_index()

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,average,Average
new_index,,,,,,,,,,,,,,
0,male,99,group E,associate's degree,standard,none,72,57,62,3.60,99,11,63.67,63.67
1,female,49,group E,associate's degree,standard,completed,95,89,92,43.77,49,16,92.00,92.00
2,male,35,group A,high school,free/reduced,none,45,47,49,64.67,35,58,47.00,47.00
3,female,52,group E,bachelor's degree,standard,completed,99,100,100,22.97,52,57,99.67,99.67
4,female,96,group D,master's degree,standard,none,92,100,100,73.07,96,32,97.33,97.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,87,group C,bachelor's degree,standard,completed,59,64,75,82.78,87,80,66.00,66.00
996,male,92,group C,associate's degree,standard,none,74,73,67,88.34,92,30,71.33,71.33
997,male,15,group A,some college,free/reduced,completed,50,47,54,56.22,15,16,50.33,50.33
998,female,92,group C,some high school,standard,completed,59,54,67,36.50,92,64,60.00,60.00
999,female,72,group A,some college,free/reduced,none,61,60,57,17.99,72,36,59.33,59.33

In [158]:
# sort index descending
df_exams.sort_index(ascending = True, inplace = True)
df_exams

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score1,score2,average,Average
new_index,,,,,,,,,,,,,,
0,male,99,group E,associate's degree,standard,none,72,57,62,3.60,99,11,63.67,63.67
1,female,49,group E,associate's degree,standard,completed,95,89,92,43.77,49,16,92.00,92.00
2,male,35,group A,high school,free/reduced,none,45,47,49,64.67,35,58,47.00,47.00
3,female,52,group E,bachelor's degree,standard,completed,99,100,100,22.97,52,57,99.67,99.67
4,female,96,group D,master's degree,standard,none,92,100,100,73.07,96,32,97.33,97.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,87,group C,bachelor's degree,standard,completed,59,64,75,82.78,87,80,66.00,66.00
996,male,92,group C,associate's degree,standard,none,74,73,67,88.34,92,30,71.33,71.33
997,male,15,group A,some college,free/reduced,completed,50,47,54,56.22,15,16,50.33,50.33
998,female,92,group C,some high school,standard,completed,59,54,67,36.50,92,64,60.00,60.00
999,female,72,group A,some college,free/reduced,none,61,60,57,17.99,72,36,59.33,59.33

# Rename Column

In [159]:
df_exams.rename(columns = {'gender':'Gender'}, inplace = True)
df_exams

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score1,score2,average,Average
new_index,,,,,,,,,,,,,,
0,male,99,group E,associate's degree,standard,none,72,57,62,3.60,99,11,63.67,63.67
1,female,49,group E,associate's degree,standard,completed,95,89,92,43.77,49,16,92.00,92.00
2,male,35,group A,high school,free/reduced,none,45,47,49,64.67,35,58,47.00,47.00
3,female,52,group E,bachelor's degree,standard,completed,99,100,100,22.97,52,57,99.67,99.67
4,female,96,group D,master's degree,standard,none,92,100,100,73.07,96,32,97.33,97.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,87,group C,bachelor's degree,standard,completed,59,64,75,82.78,87,80,66.00,66.00
996,male,92,group C,associate's degree,standard,none,74,73,67,88.34,92,30,71.33,71.33
997,male,15,group A,some college,free/reduced,completed,50,47,54,56.22,15,16,50.33,50.33
998,female,92,group C,some high school,standard,completed,59,54,67,36.50,92,64,60.00,60.00
999,female,72,group A,some college,free/reduced,none,61,60,57,17.99,72,36,59.33,59.33

In [160]:
# update 2 or more column
df_exams.rename(columns = {'math score' : 'MS', 'reading score' : 'RS', 'writing score' : 'WS'}, inplace = True)
df_exams

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score1,score2,average,Average
new_index,,,,,,,,,,,,,,
0,male,99,group E,associate's degree,standard,none,72,57,62,3.60,99,11,63.67,63.67
1,female,49,group E,associate's degree,standard,completed,95,89,92,43.77,49,16,92.00,92.00
2,male,35,group A,high school,free/reduced,none,45,47,49,64.67,35,58,47.00,47.00
3,female,52,group E,bachelor's degree,standard,completed,99,100,100,22.97,52,57,99.67,99.67
4,female,96,group D,master's degree,standard,none,92,100,100,73.07,96,32,97.33,97.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,87,group C,bachelor's degree,standard,completed,59,64,75,82.78,87,80,66.00,66.00
996,male,92,group C,associate's degree,standard,none,74,73,67,88.34,92,30,71.33,71.33
997,male,15,group A,some college,free/reduced,completed,50,47,54,56.22,15,16,50.33,50.33
998,female,92,group C,some high school,standard,completed,59,54,67,36.50,92,64,60.00,60.00
999,female,72,group A,some college,free/reduced,none,61,60,57,17.99,72,36,59.33,59.33

# Rename Index

In [164]:
#rename index 0,1,2 and update the dataframe
df_exams.rename(index={0 : 'A', 1 : 'B', 2 : 'C'}, inplace = True)
df_exams.head(3)

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score1,score2,average,Average
new_index,,,,,,,,,,,,,,
A,male,99,group E,associate's degree,standard,none,72,57,62,3.60,99,11,63.67,63.67
B,female,49,group E,associate's degree,standard,completed,95,89,92,43.77,49,16,92.00,92.00
C,male,35,group A,high school,free/reduced,none,45,47,49,64.67,35,58,47.00,47.00