In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('players_20.csv')
df

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18273,245006,https://sofifa.com/player/245006/shuai-shao/20...,Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
18274,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
18275,252332,https://sofifa.com/player/252332/wei-zhang/20/...,Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
18276,251110,https://sofifa.com/player/251110/haijian-wang/...,Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
18277,233449,https://sofifa.com/player/233449/ximing-pan/20...,Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [3]:
df.set_index('short_name', inplace = True)

In [4]:
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [5]:
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

# Selecting a single value
## loc[row_label, col_label]

In [6]:
df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [7]:
df.loc['L. Messi', 'height_cm']

np.int64(170)

In [8]:
df.loc['Cristiano Ronaldo', 'weight_kg']

np.int64(83)

In [9]:
# get all the rows inside the 'height_cm' column
# : means all indexes
df.loc[:, 'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [10]:
df.loc['L. Messi',:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

# Selecting with a list of values

In [11]:
df.loc[['L. Messi', "Cristiano Ronaldo"]]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [12]:
df.loc[['L. Messi', "Cristiano Ronaldo"], 'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [13]:
df.loc['L. Messi', ['height_cm', 'weight_kg']]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [14]:
df.loc[['L. Messi', "Cristiano Ronaldo"], ['height_cm', 'weight_kg']]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

# Selecting a range of data with slicing
### start:stop:step (start and stop are included)

In [15]:
players = ['L. Messi', 'Cristiano Ronaldo']
df.loc[players, 'age':'club'] #slice column labels

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [16]:
columns = ['age','dob','height_cm','weight_kg']
#select top 10 players
df.index[:10]
df.loc['L. Messi':'M. Salah', columns]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

# Selecting with conditions

In [17]:
columns = ['age','dob','height_cm','weight_kg']
# select player with height > 180 cm
df.loc[df['height_cm'] > 180, columns]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [18]:
# multiple conditions
df.loc[(df['height_cm'] > 180) & (df['nationality'] == 'Argentina')]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Icardi,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter
G. Higuaín,Gonzalo Gerardo Higuaín,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,Nicolás Hernán Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,Gerónimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
...,...,...,...,...,...,...,...
T. Durso,Tomás Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata
J. Hass,Joaquín Hass,21,1998-03-27,186,88,Argentina,Club Atlético Colón
R. Ferrario,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club Atlético Huracán
L. Finochietto,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors
N. Forastiero,Nicolás Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors

# Selecting elements by index position .iloc()
### .iloc[row_number, col_number]

In [19]:
df.iloc[0, 3]

np.int64(170)

In [20]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [21]:
# get weight of Cr Ronaldo
df.iloc[1,4] #column numbers index, 0, 1, 2, 3, 4...

np.int64(83)

In [22]:
df.iloc[:, 3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [23]:
df.iloc[0, :]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

# Selecting with a list of values

In [24]:
df.iloc[[0,1],:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [25]:
df.iloc[[0,1],3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [26]:
df.iloc[0,[3,4]]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [27]:
df.iloc[[0,1],[3,4]]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

# Selecting a range of data with slice
### start:stop (start is included and stop is excluded)

In [28]:
players = [0,1]
df.iloc[players, 1:7] #(1:6+1)

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [29]:
columns = [1,2,3,4]
df.iloc[0:10, columns]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

# Selecting with conditions
### .iloc() cannot accept a boolean series, but only a boolean list. We have to use the list() function to convert a series into a boolean list.

In [30]:
columns = [1,2,3,4]
df.iloc[list(df['height_cm'] > 180)]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [31]:
df.iloc[list((df['height_cm'] > 180) & (df['nationality'] == 'Argentina'))]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Icardi,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter
G. Higuaín,Gonzalo Gerardo Higuaín,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,Nicolás Hernán Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,Gerónimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
...,...,...,...,...,...,...,...
T. Durso,Tomás Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata
J. Hass,Joaquín Hass,21,1998-03-27,186,88,Argentina,Club Atlético Colón
R. Ferrario,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club Atlético Huracán
L. Finochietto,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors
N. Forastiero,Nicolás Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors

# Setting a new value for a cell in a DataFrame

In [32]:
#update height of L. Messi
df.loc['L. Messi', 'height_cm'] = 175

In [33]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [34]:
# setting height of all players
df.loc[:, 'height_cm'] = 190

In [35]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,190,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,190,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,190,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,190,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,190,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,190,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,190,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,190,78,China PR,Hebei China Fortune FC

# Setting value to an entire row

In [36]:
df.loc['Pan Ximing',:]

long_name                         潘喜明
age                                26
dob                        1993-01-11
height_cm                         190
weight_kg                          78
nationality                  China PR
club           Hebei China Fortune FC
Name: Pan Ximing, dtype: object

In [37]:
# setting null values to all columns
df.loc['Pan Ximing',:] = np.nan

In [38]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,190.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,190.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,190.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,190.0,87.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,190.0,74.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22.0,1997-03-10,190.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,190.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,190.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,190.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Set values for multiple cells

In [39]:
df.loc[['L. Messi', 'Cristiano Ronaldo'], ['height_cm']] = 175

In [40]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,190.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,190.0,87.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,190.0,74.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22.0,1997-03-10,190.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,190.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,190.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,190.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Set Values for rows matching a condition

In [41]:
columns = ['age','dob','height_cm','weight_kg']
df.loc[df['height_cm'] > 180, columns] = 0

In [42]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,0.0,0,0.0,0.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,0.0,0,0.0,0.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,0.0,0,0.0,0.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,0.0,0,0.0,0.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,0.0,0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df = pd.read_csv('players_20.csv')
df.set_index('short_name', inplace = True)
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# Drop Row

In [44]:
#axis parameter
#df.drop('L. Messi', axis = 0) # 0 - rows, 1 - columns

df.drop(index = ['L. Messi'])

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [45]:
# drop 2 or more rows
df.drop(['L. Messi', 'Cristiano Ronaldo'], axis = 0, inplace = True)

In [46]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# Drop columns

In [48]:
df.drop('long_name', axis = 1)
df.drop(columns = ['long_name'])

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
Neymar Jr,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...
Shao Shuai,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [49]:
# dropping columns by position/index (drop last column)
df.columns[[-1]]
df.drop(df.columns[[-1]], axis = 1)

,long_name,age,dob,height_cm,weight_kg,nationality
short_name,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany
...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR
Zhang Wei,张威,19,2000-05-16,186,75,China PR
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR

In [50]:
df.drop(['long_name', 'dob'], axis = 1, inplace = True)

In [51]:
df

,age,height_cm,weight_kg,nationality,club
short_name,,,,,
Neymar Jr,27,175,68,Brazil,Paris Saint-Germain
J. Oblak,26,188,87,Slovenia,Atlético Madrid
E. Hazard,28,175,74,Belgium,Real Madrid
K. De Bruyne,28,181,70,Belgium,Manchester City
M. ter Stegen,27,187,85,Germany,FC Barcelona
...,...,...,...,...,...
Shao Shuai,22,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,22,177,66,China PR,Shanghai SIPG FC
Zhang Wei,19,186,75,China PR,Hebei China Fortune FC
Wang Haijian,18,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,26,182,78,China PR,Hebei China Fortune FC

# Creating Random Samples

In [52]:
df = pd.read_csv('players_20.csv')
df.set_index('short_name', inplace = True)
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# sample()

In [56]:
# extract 10 random samples from the nationality column
df['nationality'].sample(10, random_state = 99)

short_name
R. Alvarado               Mexico
Qiao Wei                China PR
E. Paredes                 Chile
K. Stoyanov             Bulgaria
M. Chudý                Slovakia
D. Sundaram                India
R. Gagliardini             Italy
G. Debeljuh              Croatia
Kim Seung Yong    Korea Republic
M. Hansen                Denmark
Name: nationality, dtype: object

In [59]:
# extract a random 20% sample from the dataframe
df.sample(frac = 0.2, random_state = 12)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Y. Thoelen,Yannick Thoelen,28,1990-07-18,188,89,Belgium,KV Mechelen
M. Nadé,Mickaël Nadé,20,1999-03-04,188,80,France,AS Saint-Étienne
V. García,Víctor Hugo García Hernández,25,1994-06-11,178,71,Venezuela,Vitória Guimarães
M. Gyamfi,Maxwell Gyamfi,19,2000-01-18,185,75,Germany,VfL Bochum 1848
W. Cyprien,Wylan Cyprien,24,1995-01-28,180,75,France,OGC Nice
...,...,...,...,...,...,...,...
H. Kadish,Hassan Kadish,26,1992-09-26,179,73,Saudi Arabia,Al Hilal
A. Chapman,Aaron Chapman,29,1990-05-29,203,92,England,Peterborough United
I. Ezekiel,Imoh Ezekiel,25,1993-10-24,178,70,Nigeria,KV Kortrijk
H. Sakai,酒井 宏樹,29,1990-04-12,183,70,Japan,Olympique de Marseille
C. Keșerü,Claudiu Andrei Keșerü,32,1986-12-02,178,71,Romania,Romania

In [61]:
# upsample: increasing the sampling rate -> frac > 1 (NOTE : replace parameter should be set to TRUE for frac > 1.)
df.sample(frac = 2, replace = True, random_state = 9) # doubling the number of rows

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Charles,Charles Dias De Oliveira,35,1984-04-04,179,76,Brazil,SD Eibar
M. Wintzheimer,Manuel Wintzheimer,20,1999-01-10,180,77,Germany,Hamburger SV
D. Chatziisaias,Dimitris Chatziisaias,26,1992-09-21,193,77,Greece,Çaykur Rizespor
W. Dutoit,William Dutoit,30,1988-09-18,181,76,France,KV Oostende
S. Burchert,Sascha Burchert,29,1989-10-30,187,78,Germany,SpVgg Greuther Fürth
...,...,...,...,...,...,...,...
S. Kind Mikalsen,Simen Kind Mikalsen,26,1993-05-04,185,81,Norway,Lillestrøm SK
N. Atangana,Nigel Atangana,29,1989-09-09,187,72,France,Exeter City
C. Lombardi,Cristiano Lombardi,23,1995-08-19,180,75,Italy,US Salernitana 1919
D. Prokop,Dominik Prokop,22,1997-06-02,171,68,Austria,FK Austria Wien
E. Kachunga,Elias Kachunga,27,1992-04-22,178,74,DR Congo,Huddersfield Town

# Filter a dataframe using query()

In [64]:
df.query("age > 34")
#equivalent boolean slicing
df[df['age'] > 34]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
...,...,...,...,...,...,...,...
N. Hunt,Nicky Hunt,35,1983-09-03,185,86,England,Crewe Alexandra
K. Ogi,荻 晃太,36,1983-05-05,185,76,Japan,Vissel Kobe
J. McCombe,Jamie McCombe,36,1983-01-01,196,79,England,Lincoln City
G. Maley,Gary Maley,36,1982-08-03,188,90,Scotland,Livingston FC
Zhou Ting,周挺,40,1979-02-05,182,73,China PR,Dalian YiFang FC

In [68]:
df.query('age > 34 & nationality == "Italy"')
df[(df['age'] > 34) & (df['nationality'] == 'Italy')] #equivalent boolean slicing

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC
C. Maggio,Christian Maggio,37,1982-02-11,184,79,Italy,Benevento
D. Dainelli,Dario Dainelli,40,1979-06-09,191,78,Italy,Livorno
F. Marchetti,Federico Marchetti,36,1983-02-07,188,83,Italy,Genoa
F. Peluso,Federico Peluso,35,1984-01-20,188,82,Italy,Sassuolo
C. Terzi,Claudio Terzi,35,1984-06-19,180,69,Italy,Spezia
A. Rosina,Alessandro Rosina,35,1984-01-31,170,69,Italy,US Salernitana 1919
D. Maietta,Domenico Maietta,36,1982-08-03,184,75,Italy,Empoli
A. Cordaz,Alex Cordaz,36,1983-01-01,188,83,Italy,Crotone
S. Floccari,Sergio Floccari,37,1981-11-12,180,79,Italy,SPAL
M. Iori,Manuel Iori,37,1982-03-12,182,72,Italy,Cittadella
M. Stefani,Mirco Stefani,35,1984-01-25,180,80,Italy,Pordenone
G. Pegolo,Gianluca Pegolo,38,1981-03-25,183,76,Italy,Sassuolo
D. Gastaldello,Daniele Gastaldello,36,1983-06-25,185,77,Italy,Brescia
D. Moscardelli,Davide Moscardelli,39,1980-02-03,185,80,Italy,Pisa
E. Calaiò,Emanuele Calaiò,37,1982-01-08,179,75,Italy,US Salernitana 1919
D. Croce,Daniele Croce,36,1982-09-09,173,70,Italy,US Cremonese
A. Rosati,Antonio Rosati,36,1983-06-26,195,88,Italy,Torino
F. Mazzeo,Fabio Mazzeo,35,1983-07-24,177,77,Italy,Livorno
M. De Agostini,Michele De Agostini,35,1983-11-27,180,78,Italy,Pordenone
A. Pomini,Alberto Pomini,38,1981-03-17,185,80,Italy,Venezia FC
F. Evacuo,Felice Evacuo,36,1982-08-23,187,88,Italy,Trapani
G. Munari,Gianni Munari,36,1983-06-24,190,84,Italy,Parma
L. Pagliarulo,Luca Pagliarulo,35,1984-02-29,187,80,Italy,Trapani
C. Del Grosso,Cristiano Del Grosso,36,1983-03-24,171,66,Italy,Pescara
R. Vitiello,Roberto Vitiello,36,1983-05-08,176,72,Italy,Castellammare di Stabia
A. Bruno,Alessandro Bruno,35,1983-07-04,180,70,Italy,Pescara
T. Berni,Tommaso Berni,36,1983-03-06,185,80,Italy,Inter
P. Gori,Pier Graziano Gori,39,1980-05-10,189,83,Italy,Benevento
S. Farelli,Simone Farelli,36,1983-02-19,186,82,Italy,Pescara

In [71]:
df.query("not(age > 34)") #age less then 34
df[~(df['age'] > 34)] #equivalent boolean slicing

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [73]:
# convert height to meters and select those with height aboce 1.8
df.query("height_cm/100 > 1.8")
df[df['height_cm']/100 > 1.8]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [80]:
# select players that were born after 1990

# check out data types
df.dtypes
# convert 'dob' column to datetime type
df['dob'] = df['dob'].astype('datetime64[ns]')
df['dob'].dt.year

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int32

In [84]:
df.query('dob.dt.year > 1990')
df[df['dob'].dt.year > 1990] # boolean equivalent slicing

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# apply() method

In [85]:
# use numpy function and apply it to a series
df['age'].apply(np.sqrt)

short_name
L. Messi             5.656854
Cristiano Ronaldo    5.830952
Neymar Jr            5.196152
J. Oblak             5.099020
E. Hazard            5.291503
                       ...
Shao Shuai           4.690416
Xiao Mingjie         4.690416
Zhang Wei            4.358899
Wang Haijian         4.242641
Pan Ximing           5.099020
Name: age, Length: 18278, dtype: float64

In [86]:
# create own function and apply it to dataframe
def calculate_bmi(row): #row is used here as the dataframe, could replace by df. 
    return row['weight_kg']/(row['height_cm']/100)**2

In [87]:
df.apply(calculate_bmi, axis = 1) #axis = 1 means that this function uses operations between 2 or more columns

short_name
L. Messi             24.913495
Cristiano Ronaldo    23.735308
Neymar Jr            22.204082
J. Oblak             24.615211
E. Hazard            24.163265
                       ...
Shao Shuai           22.835010
Xiao Mingjie         21.066743
Zhang Wei            21.678807
Wang Haijian         21.621622
Pan Ximing           23.547881
Length: 18278, dtype: float64

In [88]:
df = pd.read_csv('players_20.csv')
df.set_index('short_name', inplace = True)
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# lambda Function - when we need to use the function temporarily

In [89]:
# basic function
def sum_values(a,b):
    return a + b

In [90]:
sum_values(2,3)

5

In [91]:
# lambda function(one liner)
sum_values_lambda = lambda a,b:a+b

In [92]:
sum_values_lambda(2,3)

5

# apply() + lambda function

In [95]:
df['height_cm'].apply(lambda x:x/100)

# alternative

# df['height_cm']/100

short_name
L. Messi             1.70
Cristiano Ronaldo    1.87
Neymar Jr            1.75
J. Oblak             1.88
E. Hazard            1.75
                     ...
Shao Shuai           1.86
Xiao Mingjie         1.77
Zhang Wei            1.86
Wang Haijian         1.85
Pan Ximing           1.82
Name: height_cm, Length: 18278, dtype: float64

In [98]:
df['long_name'].apply(lambda x:x.upper())

#alternative with str attribute
# df['long_name'].str.upper()

short_name
L. Messi                  LIONEL ANDRÉS MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
                                    ...
Shao Shuai                                            邵帅
Xiao Mingjie                                MINGJIE XIAO
Zhang Wei                                             张威
Wang Haijian                                         汪海健
Pan Ximing                                           潘喜明
Name: long_name, Length: 18278, dtype: object

In [101]:
df['dob'] = df['dob'].astype('datetime64[ns]')
df.dtypes

long_name              object
age                     int64
dob            datetime64[ns]
height_cm               int64
weight_kg               int64
nationality            object
club                   object
dtype: object

In [102]:
df['dob'].apply(lambda x:x.year)

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int64

In [103]:
df['dob'].dt.year

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int32

In [115]:
df.apply(lambda x: x['weight_kg']/((x['height_cm']/100)**2), axis = 1)

short_name
L. Messi             24.913495
Cristiano Ronaldo    23.735308
Neymar Jr            22.204082
J. Oblak             24.615211
E. Hazard            24.163265
                       ...
Shao Shuai           22.835010
Xiao Mingjie         21.066743
Zhang Wei            21.678807
Wang Haijian         21.621622
Pan Ximing           23.547881
Length: 18278, dtype: float64

# Making a copy of a dataframe using copy()

### deep = True

In [117]:
df_copy = df.copy() #Deep = True by default (Modifications in the dataframe is not going to be reflected in the copied dataframe.)

In [119]:
df.loc['L. Messi', 'height_cm'] = 180

In [120]:
df_copy # doesn't change Messi's height

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

### deep = False

In [122]:
df_shallow_copy = df.copy(deep = False)

In [123]:
df.loc['Cristiano Ronaldo', 'height_cm'] = 200

In [125]:
df_shallow_copy # C Ronaldo height is changed in shallow copy when original is changed

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,200,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# Simple Assignment Copy

In [126]:
df_new_copy = df

In [127]:
df.loc['Neymar Jr', 'height_cm'] = 190

In [128]:
df_new_copy # Assignment made a shallow copy, equalt to deep = False

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,200,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC